name: Supabase Keep Alive

on:
  schedule:
    # 5일 주기(*/5)보다 더 안전하게 3일마다(*/3) 실행되도록 변경했습니다.
    - cron: '0 0 */3 * *'  
  workflow_dispatch: # 수동 실행 가능

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Insert Row to ConnectHist
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/ConnectHist" \
            -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'
          
          echo "ConnectHist 테이블에 데이터가 성공적으로 추가되었습니다!"
